let uncleTomMC = [
  Status code: 200 0
{'status': {'code': '0', 'msg': 'OK', 'credits': '34', 'remaining_credits': '8060'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '64', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '36', 'relevance': '56'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '27'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '13', 'relevance': '20'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '17'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '14'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '12'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '8'}]}
Status code: 200 1
{'status': {'code': '0', 'msg': 'OK', 'credits': '11', 'remaining_credits': '8049'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '76'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '35'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '24'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '24'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '12'}]}
Status code: 200 2
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '8031'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '21', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '18', 'relevance': '86'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '17', 'relevance': '81'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '71'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '57'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '48'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '24'}]}
Status code: 200 3
{'status': {'code': '0', 'msg': 'OK', 'credits': '38', 'remaining_credits': '7993'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '66', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '48', 'relevance': '73'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '27'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '18'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '12', 'relevance': '18'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '12'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '11'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '9'}]}
Status code: 200 4
{'status': {'code': '0', 'msg': 'OK', 'credits': '30', 'remaining_credits': '7963'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '45', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '21', 'relevance': '47'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '19', 'relevance': '42'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '42'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '14', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '4'}]}
Status code: 200 5
{'status': {'code': '0', 'msg': 'OK', 'credits': '30', 'remaining_credits': '7933'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '44', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '59'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '48'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '34'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '30'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '27'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '20'}]}
Status code: 200 6
{'status': {'code': '0', 'msg': 'OK', 'credits': '43', 'remaining_credits': '7890'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '43', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '43', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '65'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '21', 'relevance': '49'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '18', 'relevance': '42'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '35'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '33'}]}
Status code: 200 7
{'status': {'code': '0', 'msg': 'OK', 'credits': '53', 'remaining_credits': '7837'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '49', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '38', 'relevance': '78'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '23', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '43'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '19', 'relevance': '39'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '37'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '24'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '20'}]}
Status code: 200 8
{'status': {'code': '0', 'msg': 'OK', 'credits': '55', 'remaining_credits': '7782'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '62', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '57', 'relevance': '92'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '55', 'relevance': '89'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '32', 'relevance': '52'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '42'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '23', 'relevance': '37'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '22', 'relevance': '35'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '27'}]}
Status code: 200 9
{'status': {'code': '0', 'msg': 'OK', 'credits': '33', 'remaining_credits': '7749'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '39', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '37', 'relevance': '95'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '36', 'relevance': '92'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '56'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '15', 'relevance': '38'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '28'}]}
Status code: 200 10
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '7703'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '57', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '44', 'relevance': '77'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '22', 'relevance': '39'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '21', 'relevance': '37'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '23'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '21'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '16'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '14'}]}
Status code: 200 11
{'status': {'code': '0', 'msg': 'OK', 'credits': '56', 'remaining_credits': '7647'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '51', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '49', 'relevance': '96'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '46', 'relevance': '90'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '28', 'relevance': '55'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '25', 'relevance': '49'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '43'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '16', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '20'}]}
Status code: 200 12
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '7618'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '57', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '30', 'relevance': '53'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '17', 'relevance': '30'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '28'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '16', 'relevance': '28'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '14'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '7'}]}
Status code: 200 13
{'status': {'code': '0', 'msg': 'OK', 'credits': '34', 'remaining_credits': '7584'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '44', 'relevance': '96'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '39'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '28'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '24'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '11'}]}
Status code: 200 14
{'status': {'code': '0', 'msg': 'OK', 'credits': '53', 'remaining_credits': '7531'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '84', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '71', 'relevance': '85'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '43'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '35', 'relevance': '42'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '33', 'relevance': '39'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '24'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '20', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '14'}]}
Status code: 200 15
{'status': {'code': '0', 'msg': 'OK', 'credits': '61', 'remaining_credits': '7470'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '67', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '66', 'relevance': '99'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '50', 'relevance': '75'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '33', 'relevance': '49'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '32', 'relevance': '48'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '32', 'relevance': '48'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '32', 'relevance': '48'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '21'}]}
Status code: 200 16
{'status': {'code': '0', 'msg': 'OK', 'credits': '57', 'remaining_credits': '7413'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '49', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '42', 'relevance': '86'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '35', 'relevance': '71'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '32', 'relevance': '65'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '30', 'relevance': '61'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '24', 'relevance': '49'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '27'}]}
Status code: 200 17
{'status': {'code': '0', 'msg': 'OK', 'credits': '52', 'remaining_credits': '7361'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '50', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '49', 'relevance': '98'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '32', 'relevance': '64'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '31', 'relevance': '62'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '30', 'relevance': '60'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '23', 'relevance': '46'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '24'}]}
Status code: 200 18
{'status': {'code': '0', 'msg': 'OK', 'credits': '67', 'remaining_credits': '7294'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '87', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '55', 'relevance': '63'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '50', 'relevance': '57'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '48', 'relevance': '55'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '39', 'relevance': '45'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '32'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '24', 'relevance': '28'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '22', 'relevance': '25'}]}
Status code: 200 19
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '7246'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '56', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '51', 'relevance': '91'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '38', 'relevance': '68'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '31', 'relevance': '55'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '27', 'relevance': '48'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '24', 'relevance': '43'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '34'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '27'}]}
Status code: 200 20
{'status': {'code': '0', 'msg': 'OK', 'credits': '15', 'remaining_credits': '7231'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '14'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 21
{'status': {'code': '0', 'msg': 'OK', 'credits': '23', 'remaining_credits': '7208'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '48', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '54'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '23'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '10'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '8'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '2'}]}
Status code: 200 22
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '7184'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '40', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '72'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '35'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '14', 'relevance': '35'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '14', 'relevance': '35'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '32'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '28'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '22'}]}
Status code: 200 23
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '7163'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '36', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '36', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '29', 'relevance': '81'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '36'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '22'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '14'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '11'}]}
Status code: 200 24
{'status': {'code': '0', 'msg': 'OK', 'credits': '16', 'remaining_credits': '7147'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '36', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '25', 'relevance': '69'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '25'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '19'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '11'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '11'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '11'}]}
Status code: 200 25
{'status': {'code': '0', 'msg': 'OK', 'credits': '42', 'remaining_credits': '7105'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '79', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '52', 'relevance': '66'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '46', 'relevance': '58'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '22', 'relevance': '28'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '15'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '13'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '10'}]}
Status code: 200 26
{'status': {'code': '0', 'msg': 'OK', 'credits': '25', 'remaining_credits': '7080'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '36', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '34', 'relevance': '94'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '30', 'relevance': '83'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '31'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '17'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '8'}]}
Status code: 200 27
{'status': {'code': '0', 'msg': 'OK', 'credits': '47', 'remaining_credits': '7033'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '57', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '38', 'relevance': '67'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '35', 'relevance': '61'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '27', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '46'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '24', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '23', 'relevance': '40'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '19'}]}
Status code: 200 28
{'status': {'code': '0', 'msg': 'OK', 'credits': '25', 'remaining_credits': '7008'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '29', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '22', 'relevance': '76'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '62'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '59'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '52'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '48'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '14', 'relevance': '48'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '24'}]}
Status code: 200 29
{'status': {'code': '0', 'msg': 'OK', 'credits': '33', 'remaining_credits': '6975'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '25', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '24', 'relevance': '96'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '80'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '19', 'relevance': '76'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '68'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '16', 'relevance': '64'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '28'}]}
Status code: 200 30
{'status': {'code': '0', 'msg': 'OK', 'credits': '20', 'remaining_credits': '6955'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '79'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '16', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '62'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '46'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '4'}]}
Status code: 200 31
{'status': {'code': '0', 'msg': 'OK', 'credits': '27', 'remaining_credits': '6928'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '47', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '25', 'relevance': '53'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '22', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '45'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '18', 'relevance': '38'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '18', 'relevance': '38'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '23'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '13'}]}
Status code: 200 32
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '6904'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '40', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '29', 'relevance': '72'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '28', 'relevance': '70'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '17', 'relevance': '42'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '16', 'relevance': '40'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '35'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '22'}]}
Status code: 200 33
{'status': {'code': '0', 'msg': 'OK', 'credits': '39', 'remaining_credits': '6865'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '57', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '56', 'relevance': '98'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '43', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '33', 'relevance': '58'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '25', 'relevance': '44'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '21'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '19'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '16'}]}
Status code: 200 34
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '6844'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '49', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '37', 'relevance': '76'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '35', 'relevance': '71'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '31', 'relevance': '63'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '25', 'relevance': '51'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '23', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '35'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '31'}]}
Status code: 200 35
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '6823'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '29', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '28', 'relevance': '97'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '21', 'relevance': '72'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '59'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '17', 'relevance': '59'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '34'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '31'}]}
Status code: 200 36
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '6802'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '28', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '21', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '54'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '36'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '32'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '25'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '11'}]}
Status code: 200 37
{'status': {'code': '0', 'msg': 'OK', 'credits': '33', 'remaining_credits': '6769'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '63', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '49', 'relevance': '78'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '36', 'relevance': '57'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '35', 'relevance': '56'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '31', 'relevance': '49'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '25', 'relevance': '40'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '20', 'relevance': '32'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '22'}]}
Status code: 200 38
{'status': {'code': '0', 'msg': 'OK', 'credits': '32', 'remaining_credits': '6737'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '29', 'relevance': '63'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '61'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '25', 'relevance': '54'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '21', 'relevance': '46'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '46'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '37'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '35'}]}
Status code: 200 39
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '6715'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '31', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '28', 'relevance': '90'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '24', 'relevance': '77'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '68'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '52'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '52'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '39'}]}
Status code: 200 40
{'status': {'code': '0', 'msg': 'OK', 'credits': '20', 'remaining_credits': '6695'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '40', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '70'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '26', 'relevance': '65'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '15', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '28'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '22'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '18'}]}
Status code: 200 41
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '6674'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '23', 'relevance': '88'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '62'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '16', 'relevance': '62'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '14', 'relevance': '54'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '35'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '12'}]}
Status code: 200 42
{'status': {'code': '0', 'msg': 'OK', 'credits': '27', 'remaining_credits': '6647'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '34', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '27', 'relevance': '79'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '22', 'relevance': '65'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '20', 'relevance': '59'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '35'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '32'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '24'}]}
Status code: 200 43
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '6635'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '74'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '26'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '16'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '11'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '5'}]}
Status code: 200 44
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '6604'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '65', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '55'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '32', 'relevance': '49'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '43'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '24', 'relevance': '37'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '15', 'relevance': '23'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '23'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '14'}]}
]