let draculaMC = [
  Status code: 200 0
{'status': {'code': '0', 'msg': 'OK', 'credits': '47', 'remaining_credits': '16114'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '78'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '35', 'relevance': '76'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '57'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '19', 'relevance': '41'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '28'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '26'}]}
Status code: 200 1
{'status': {'code': '0', 'msg': 'OK', 'credits': '45', 'remaining_credits': '16069'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '43', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '38', 'relevance': '88'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '23', 'relevance': '53'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '42'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '37'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '30'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '28'}]}
Status code: 200 2
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '16023'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '63', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '53', 'relevance': '84'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '39', 'relevance': '62'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '28', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '41'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '26', 'relevance': '41'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '17', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '14'}]}
Status code: 200 3
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '15975'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '40', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '34', 'relevance': '85'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '31', 'relevance': '78'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '30', 'relevance': '75'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '27', 'relevance': '68'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '26', 'relevance': '65'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '62'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '30'}]}
Status code: 200 4
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '15946'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '86', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '69', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '23', 'relevance': '27'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '15'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '6'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '6'}]}
Status code: 200 5
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '15900'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '52', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '39', 'relevance': '75'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '36', 'relevance': '69'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '26', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '20', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '13'}]}
Status code: 200 6
{'status': {'code': '201', 'msg': 'Resource not supported', 'credits': '0', 'remaining_credits': '15900'}}
Status code: 200 7
{'status': {'code': '0', 'msg': 'OK', 'credits': '51', 'remaining_credits': '15849'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '64', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '61', 'relevance': '95'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '47', 'relevance': '73'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '33', 'relevance': '52'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '28', 'relevance': '44'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '19', 'relevance': '30'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '20'}]}
Status code: 200 8
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '15801'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '104', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '58', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '45', 'relevance': '43'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '32', 'relevance': '31'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '27', 'relevance': '26'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '24'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '19', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '11'}]}
Status code: 200 9
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '15753'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '44', 'relevance': '96'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '30', 'relevance': '65'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '27', 'relevance': '59'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '54'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '15', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '28'}]}
Status code: 200 10
{'status': {'code': '0', 'msg': 'OK', 'credits': '42', 'remaining_credits': '15711'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '45', 'relevance': '98'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '30', 'relevance': '65'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '29', 'relevance': '63'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '54'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '19', 'relevance': '41'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '18', 'relevance': '39'}]}
Status code: 200 11
{'status': {'code': '0', 'msg': 'OK', 'credits': '59', 'remaining_credits': '15652'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '86', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '57', 'relevance': '66'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '50', 'relevance': '58'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '41', 'relevance': '48'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '25', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '15'}]}
Status code: 200 12
{'status': {'code': '0', 'msg': 'OK', 'credits': '54', 'remaining_credits': '15598'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '93', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '74', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '52', 'relevance': '56'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '34', 'relevance': '37'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '22'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '20'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '16'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '6'}]}
Status code: 200 13
{'status': {'code': '0', 'msg': 'OK', 'credits': '52', 'remaining_credits': '15546'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '68', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '53', 'relevance': '78'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '41'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '37'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '32'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '19', 'relevance': '28'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '15', 'relevance': '22'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '18'}]}
Status code: 200 14
{'status': {'code': '0', 'msg': 'OK', 'credits': '47', 'remaining_credits': '15499'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '47', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '42', 'relevance': '89'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '33', 'relevance': '70'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '27', 'relevance': '57'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '55'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '18', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '28'}]}
Status code: 200 15
{'status': {'code': '0', 'msg': 'OK', 'credits': '38', 'remaining_credits': '15461'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '32', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '29', 'relevance': '91'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '91'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '27', 'relevance': '84'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '26', 'relevance': '81'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '66'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '56'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '16', 'relevance': '50'}]}
Status code: 200 16
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '15415'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '59', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '39', 'relevance': '66'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '33', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '31', 'relevance': '53'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '22', 'relevance': '37'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '20', 'relevance': '34'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '14'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '12'}]}
Status code: 200 17
{'status': {'code': '0', 'msg': 'OK', 'credits': '56', 'remaining_credits': '15359'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '74', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '42', 'relevance': '57'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '38', 'relevance': '51'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '30', 'relevance': '41'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '28', 'relevance': '38'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '27', 'relevance': '36'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '23', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '22', 'relevance': '30'}]}
Status code: 200 18
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '15313'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '53', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '46', 'relevance': '87'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '37', 'relevance': '70'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '32', 'relevance': '60'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '28', 'relevance': '53'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '27', 'relevance': '51'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '32'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '15', 'relevance': '28'}]}
Status code: 200 19
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '15265'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '31', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '61'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '27', 'relevance': '59'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '24', 'relevance': '52'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '37'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '16', 'relevance': '35'}]}
Status code: 200 20
{'status': {'code': '0', 'msg': 'OK', 'credits': '50', 'remaining_credits': '15215'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '49', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '40', 'relevance': '82'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '37', 'relevance': '76'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '30', 'relevance': '61'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '30', 'relevance': '61'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '41'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '35'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '22'}]}
Status code: 200 21
{'status': {'code': '0', 'msg': 'OK', 'credits': '44', 'remaining_credits': '15171'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '57', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '39', 'relevance': '68'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '49'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '27', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '44'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '24', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '18', 'relevance': '32'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '11'}]}
Status code: 200 22
{'status': {'code': '0', 'msg': 'OK', 'credits': '46', 'remaining_credits': '15125'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '43', 'relevance': '93'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '38', 'relevance': '83'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '35', 'relevance': '76'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '33', 'relevance': '72'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '24', 'relevance': '52'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '30'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '30'}]}
Status code: 200 23
{'status': {'code': '0', 'msg': 'OK', 'credits': '51', 'remaining_credits': '15074'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '53', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '43', 'relevance': '81'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '23', 'relevance': '43'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '28'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '17'}]}
Status code: 200 24
{'status': {'code': '0', 'msg': 'OK', 'credits': '51', 'remaining_credits': '15023'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '52', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '37', 'relevance': '71'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '34', 'relevance': '65'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '31', 'relevance': '60'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '38'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '20', 'relevance': '38'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '15'}]}
Status code: 200 25
{'status': {'code': '0', 'msg': 'OK', 'credits': '58', 'remaining_credits': '14965'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '66', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '48', 'relevance': '73'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '38', 'relevance': '58'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '37', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '34', 'relevance': '52'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '19', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '26'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '20'}]}
Status code: 200 26
{'status': {'code': '0', 'msg': 'OK', 'credits': '62', 'remaining_credits': '14903'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '63', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '54', 'relevance': '86'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '48', 'relevance': '76'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '45', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '43', 'relevance': '68'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '35', 'relevance': '56'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '33', 'relevance': '52'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '27'}]}
Status code: 200 27
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '14900'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '88'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '12'}]}
]