let janeEyreMC = [
  Status code: 200 0
{'status': {'code': '0', 'msg': 'OK', 'credits': '16', 'remaining_credits': '14884'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '17', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '16', 'relevance': '94'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '82'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '82'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '71'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '65'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '47'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '35'}]}
Status code: 200 1
{'status': {'code': '0', 'msg': 'OK', 'credits': '23', 'remaining_credits': '14861'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '27', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '93'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '24', 'relevance': '89'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '74'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '15', 'relevance': '56'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '48'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '12', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '33'}]}
Status code: 200 2
{'status': {'code': '0', 'msg': 'OK', 'credits': '26', 'remaining_credits': '14835'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '44', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '37', 'relevance': '84'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '59'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '23', 'relevance': '52'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '43'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '27'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '20'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '11'}]}
Status code: 200 3
{'status': {'code': '0', 'msg': 'OK', 'credits': '47', 'remaining_credits': '14788'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '55', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '45', 'relevance': '82'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '40', 'relevance': '73'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '39', 'relevance': '71'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '39', 'relevance': '71'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '65'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '27', 'relevance': '49'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '27'}]}
Status code: 200 4
{'status': {'code': '0', 'msg': 'OK', 'credits': '41', 'remaining_credits': '14747'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '32', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '28', 'relevance': '88'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '26', 'relevance': '81'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '24', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '25'}]}
Status code: 200 5
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '14723'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '22', 'relevance': '92'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '21', 'relevance': '88'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '19', 'relevance': '79'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '18', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '62'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '33'}]}
Status code: 200 6
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '14694'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '23', 'relevance': '96'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '22', 'relevance': '92'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '83'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '71'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '46'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '25'}]}
Status code: 200 7
{'status': {'code': '0', 'msg': 'OK', 'credits': '25', 'remaining_credits': '14669'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '36', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '32', 'relevance': '89'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '24', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '17', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '22'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '19'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '17'}]}
Status code: 200 8
{'status': {'code': '0', 'msg': 'OK', 'credits': '27', 'remaining_credits': '14642'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '44', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '66'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '27', 'relevance': '61'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '17', 'relevance': '39'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '14', 'relevance': '32'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '32'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '16'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '14'}]}
Status code: 200 9
{'status': {'code': '0', 'msg': 'OK', 'credits': '36', 'remaining_credits': '14606'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '34', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '85'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '76'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '41'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '32'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '24'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '21'}]}
Status code: 200 10
{'status': {'code': '0', 'msg': 'OK', 'credits': '53', 'remaining_credits': '14553'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '65', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '31', 'relevance': '48'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '29', 'relevance': '45'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '29', 'relevance': '45'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '34'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '19', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '14'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '6'}]}
Status code: 200 11
{'status': {'code': '0', 'msg': 'OK', 'credits': '34', 'remaining_credits': '14519'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '46', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '41'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '15', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '28'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '24'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '15'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '9'}]}
Status code: 200 12
{'status': {'code': '0', 'msg': 'OK', 'credits': '33', 'remaining_credits': '14486'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '21', 'relevance': '81'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '62'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '62'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '35'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '19'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '15'}]}
Status code: 200 13
{'status': {'code': '0', 'msg': 'OK', 'credits': '40', 'remaining_credits': '14446'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '44', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '30', 'relevance': '68'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '26', 'relevance': '59'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '23', 'relevance': '52'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '19', 'relevance': '43'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '39'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '34'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '25'}]}
Status code: 200 14
{'status': {'code': '0', 'msg': 'OK', 'credits': '41', 'remaining_credits': '14405'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '54', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '26', 'relevance': '48'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '25', 'relevance': '46'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '23', 'relevance': '43'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '19', 'relevance': '35'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '33'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '17', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '16', 'relevance': '30'}]}
Status code: 200 15
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '14374'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '40', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '36', 'relevance': '90'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '21', 'relevance': '52'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '17', 'relevance': '42'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '11', 'relevance': '28'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '25'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '25'}]}
Status code: 200 16
{'status': {'code': '0', 'msg': 'OK', 'credits': '66', 'remaining_credits': '14308'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '78', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '49', 'relevance': '63'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '35', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '28', 'relevance': '36'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '22', 'relevance': '28'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '21', 'relevance': '27'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '17'}]}
Status code: 200 17
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '14260'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '64', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '59', 'relevance': '92'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '30', 'relevance': '47'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '29', 'relevance': '45'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '27', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '18', 'relevance': '28'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '23'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '20'}]}
Status code: 200 18
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '14229'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '42', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '24', 'relevance': '57'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '43'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '17', 'relevance': '40'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '12'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '12'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '5'}]}
Status code: 200 19
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '14181'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '45', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '41', 'relevance': '91'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '34', 'relevance': '76'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '33', 'relevance': '73'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '62'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '22', 'relevance': '49'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '31'}]}
Status code: 200 20
{'status': {'code': '0', 'msg': 'OK', 'credits': '72', 'remaining_credits': '14109'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '61', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '58', 'relevance': '95'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '56', 'relevance': '92'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '55', 'relevance': '90'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '46', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '29', 'relevance': '48'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '25', 'relevance': '41'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '36'}]}
Status code: 200 21
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '14085'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '33', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '22', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '22', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '52'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '30'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '18'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '15'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '15'}]}
Status code: 200 22
{'status': {'code': '0', 'msg': 'OK', 'credits': '33', 'remaining_credits': '14052'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '49', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '48', 'relevance': '98'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '39', 'relevance': '80'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '23', 'relevance': '47'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '16'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '14'}]}
Status code: 200 23
{'status': {'code': '0', 'msg': 'OK', 'credits': '58', 'remaining_credits': '13994'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '113', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '83', 'relevance': '73'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '39', 'relevance': '35'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '37', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '35', 'relevance': '31'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '19', 'relevance': '17'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '17', 'relevance': '15'}]}
Status code: 200 24
{'status': {'code': '0', 'msg': 'OK', 'credits': '41', 'remaining_credits': '13953'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '43', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '42', 'relevance': '98'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '33', 'relevance': '77'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '32', 'relevance': '74'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '29', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '16', 'relevance': '37'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '35'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '30'}]}
Status code: 200 25
{'status': {'code': '0', 'msg': 'OK', 'credits': '35', 'remaining_credits': '13918'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '32', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '30', 'relevance': '94'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '26', 'relevance': '81'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '69'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '59'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '47'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '28'}]}
Status code: 200 26
{'status': {'code': '0', 'msg': 'OK', 'credits': '91', 'remaining_credits': '13827'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '119', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '109', 'relevance': '92'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '101', 'relevance': '85'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '98', 'relevance': '82'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '84', 'relevance': '71'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '68', 'relevance': '57'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '32', 'relevance': '27'}]}
Status code: 200 27
{'status': {'code': '0', 'msg': 'OK', 'credits': '56', 'remaining_credits': '13771'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '78', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '37'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '36'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '28', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '21', 'relevance': '27'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '14'}]}
Status code: 200 28
{'status': {'code': '0', 'msg': 'OK', 'credits': '37', 'remaining_credits': '13734'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '38', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '37', 'relevance': '97'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '76'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '26'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '26'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '11'}]}
Status code: 200 29
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '13703'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '63', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '26', 'relevance': '41'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '21', 'relevance': '33'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '29'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '13'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '11'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '11'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '10'}]}
Status code: 200 30
{'status': {'code': '0', 'msg': 'OK', 'credits': '26', 'remaining_credits': '13677'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '43', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '25', 'relevance': '58'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '23', 'relevance': '53'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '33'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '30'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '23'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '23'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '14'}]}
Status code: 200 31
{'status': {'code': '0', 'msg': 'OK', 'credits': '38', 'remaining_credits': '13639'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '96', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '48', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '28', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '27', 'relevance': '28'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '20', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '8'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '8'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '6'}]}
Status code: 200 32
{'status': {'code': '0', 'msg': 'OK', 'credits': '39', 'remaining_credits': '13600'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '52', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '47', 'relevance': '90'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '25', 'relevance': '48'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '21', 'relevance': '40'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '21', 'relevance': '40'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '18', 'relevance': '35'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '17', 'relevance': '33'}]}
Status code: 200 33
{'status': {'code': '0', 'msg': 'OK', 'credits': '75', 'remaining_credits': '13525'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '119', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '102', 'relevance': '86'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '59', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '54', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '39', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '34', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '33', 'relevance': '28'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '20', 'relevance': '17'}]}
Status code: 200 34
{'status': {'code': '0', 'msg': 'OK', 'credits': '36', 'remaining_credits': '13489'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '55', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '52', 'relevance': '95'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '32', 'relevance': '58'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '24', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '31'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '27'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '20'}]}
Status code: 200 35
{'status': {'code': '0', 'msg': 'OK', 'credits': '32', 'remaining_credits': '13457'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '38', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '95'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '32', 'relevance': '84'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '27', 'relevance': '71'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '23', 'relevance': '61'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '19', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '37'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '34'}]}
Status code: 200 36
{'status': {'code': '0', 'msg': 'OK', 'credits': '61', 'remaining_credits': '13396'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '91', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '79', 'relevance': '87'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '69', 'relevance': '76'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '37', 'relevance': '41'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '32', 'relevance': '35'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '28', 'relevance': '31'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '25', 'relevance': '27'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '23', 'relevance': '25'}]}
Status code: 200 37
{'status': {'code': '0', 'msg': 'OK', 'credits': '15', 'remaining_credits': '13381'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '38', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '76'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '29'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '21'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '5'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '5'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '3'}]}
]