let huckFinnMA = [
  Status code: 200 0
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '13369'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 1
{'status': {'code': '0', 'msg': 'OK', 'credits': '20', 'remaining_credits': '13349'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '14'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 2
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '13335'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 3
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '13323'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '8'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 4
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '13309'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '60'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '10'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 5
{'status': {'code': '0', 'msg': 'OK', 'credits': '25', 'remaining_credits': '13284'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '18'}]}
Status code: 200 6
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '13262'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '71'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 7
{'status': {'code': '0', 'msg': 'OK', 'credits': '37', 'remaining_credits': '13225'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '22', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '45'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '45'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '41'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '36'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '23'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '18'}]}
Status code: 200 8
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '13211'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '89'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 9
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '13199'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '16', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '81'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '31'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '25'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '25'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '19'}]}
Status code: 200 10
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '13175'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '76'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '59'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '41'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '35'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '29'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '18'}]}
Status code: 200 11
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '13151'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '93'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '53'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '33'}]}
Status code: 200 12
{'status': {'code': '0', 'msg': 'OK', 'credits': '17', 'remaining_credits': '13134'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '36'}]}
Status code: 200 13
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '13121'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '60'}]}
Status code: 200 14
{'status': {'code': '0', 'msg': 'OK', 'credits': '20', 'remaining_credits': '13101'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '92'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '83'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 15
{'status': {'code': '0', 'msg': 'OK', 'credits': '28', 'remaining_credits': '13073'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '73'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '53'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '20'}]}
Status code: 200 16
{'status': {'code': '0', 'msg': 'OK', 'credits': '28', 'remaining_credits': '13045'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '29', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '55'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '48'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '17'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '14'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '14'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '7'}]}
Status code: 200 17
{'status': {'code': '0', 'msg': 'OK', 'credits': '39', 'remaining_credits': '13006'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '32', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '20', 'relevance': '62'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '19', 'relevance': '59'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '34'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '28'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '28'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '25'}]}
Status code: 200 18
{'status': {'code': '0', 'msg': 'OK', 'credits': '28', 'remaining_credits': '12978'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '29', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '86'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '62'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '24'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '24'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '17'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '10'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '7'}]}
Status code: 200 19
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '12949'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '20', 'relevance': '77'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '35'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '35'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '31'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '12'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '8'}]}
Status code: 200 20
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '12920'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '96'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '19', 'relevance': '73'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '54'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '35'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '23'}]}
Status code: 200 21
{'status': {'code': '0', 'msg': 'OK', 'credits': '17', 'remaining_credits': '12903'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '88'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '62'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '13', 'relevance': '54'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '17'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '17'}]}
Status code: 200 22
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '12884'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '85'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '85'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '77'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '69'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 23
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '12865'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 24
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '12841'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '44', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '29', 'relevance': '66'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '20', 'relevance': '45'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '39'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '30'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '20'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '9'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '9'}]}
Status code: 200 25
{'status': {'code': '0', 'msg': 'OK', 'credits': '24', 'remaining_credits': '12817'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '17', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '88'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '59'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '6'}]}
Status code: 200 26
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '12795'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '18', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '17', 'relevance': '94'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '78'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '78'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '17'}]}
Status code: 200 27
{'status': {'code': '0', 'msg': 'OK', 'credits': '30', 'remaining_credits': '12765'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '22', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '86'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '32'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '32'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '27'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '9'}]}
Status code: 200 28
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '12734'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '27', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '70'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '52'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '48'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '13', 'relevance': '48'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '19'}]}
Status code: 200 29
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '12724'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '78'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '11'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 30
{'status': {'code': '0', 'msg': 'OK', 'credits': '30', 'remaining_credits': '12694'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '58'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '54'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '46'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '46'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '17'}]}
Status code: 200 31
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '12675'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '73'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '20'}]}
Status code: 200 32
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '12653'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '19', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '53'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '47'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '37'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '26'}]}
Status code: 200 33
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '12635'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 34
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '12613'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 35
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '12595'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '8', 'relevance': '89'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '22'}]}
Status code: 200 36
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '12574'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '80'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '12', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '20'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '20'}]}
Status code: 200 37
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '12553'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '20', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '19', 'relevance': '95'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '12', 'relevance': '60'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '55'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '30'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '25'}]}
Status code: 200 38
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '12535'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '27', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '74'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '41'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '37'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '26'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '26'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '19'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '11'}]}
Status code: 200 39
{'status': {'code': '202', 'msg': 'Engine internal error', 'credits': '0', 'remaining_credits': '12535'}}
Status code: 200 40
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '12513'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '25'}]}
Status code: 200 41
{'status': {'code': '0', 'msg': 'OK', 'credits': '26', 'remaining_credits': '12487'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '21', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '29'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '10'}]}
Status code: 200 42
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '12481'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '20'}]}
]