let mobyDickMC = [
  Status code: 200 0
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '19982'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '19', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '68'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '58'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '42'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '32'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '26'}]}
Status code: 200 1
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '19970'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '16', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '56'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '25'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '25'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '19'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '19'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '12'}]}
Status code: 200 2
{'status': {'code': '0', 'msg': 'OK', 'credits': '48', 'remaining_credits': '19922'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '42', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '26', 'relevance': '62'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '25', 'relevance': '60'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '22', 'relevance': '52'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '21', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '24'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '24'}]}
Status code: 200 3
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19908'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '69'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '56'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '44'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '44'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '25'}]}
Status code: 200 4
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '19902'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 5
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '19895'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '33'}]}
Status code: 200 6
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19887'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '18'}]}
Status code: 200 7
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19879'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '12'}]}
Status code: 200 8
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '19850'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '38', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '36', 'relevance': '95'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '35', 'relevance': '92'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '29', 'relevance': '76'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '28', 'relevance': '74'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '17', 'relevance': '45'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '24'}]}
Status code: 200 9
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '19837'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '24', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '54'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '12', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '25'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '21'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '12'}]}
Status code: 200 10
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '19831'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '64'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '14'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '14'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 11
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19823'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '73'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '64'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '9'}]}
Status code: 200 12
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19809'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '73'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '73'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '64'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '27'}]}
Status code: 200 13
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '19802'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 14
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '19792'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 15
{'status': {'code': '0', 'msg': 'OK', 'credits': '45', 'remaining_credits': '19747'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '37', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '34', 'relevance': '92'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '28', 'relevance': '76'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '68'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '57'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '19', 'relevance': '51'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '17', 'relevance': '46'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '15', 'relevance': '41'}]}
Status code: 200 16
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '19728'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '72'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '67'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '8', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '39'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '28'}]}
Status code: 200 17
{'status': {'code': '0', 'msg': 'OK', 'credits': '11', 'remaining_credits': '19717'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 18
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '19707'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '14'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 19
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19699'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 20
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '19690'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '38'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '12'}]}
Status code: 200 21
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19676'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '77'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '69'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '54'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '23'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '8'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 22
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '19673'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '62'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '12'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '12'}]}
Status code: 200 23
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19659'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '32', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '19'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '19'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '16'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '12'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '6'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '6'}]}
Status code: 200 24
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '19656'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '20'}]}
Status code: 200 25
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '19646'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '10', 'relevance': '71'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '64'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '64'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '29'}]}
Status code: 200 26
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19632'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '81'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '75'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '69'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '12'}]}
Status code: 200 27
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '19620'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '71'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '21'}]}
Status code: 200 28
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '19610'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '33'}]}
Status code: 200 29
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '19607'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '33'}]}
Status code: 200 30
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '19600'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '30', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '30'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '17'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '17'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '13'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '13'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '3'}]}
Status code: 200 31
{'status': {'code': '0', 'msg': 'OK', 'credits': '42', 'remaining_credits': '19558'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '39', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '25', 'relevance': '64'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '18', 'relevance': '46'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '18', 'relevance': '46'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '16', 'relevance': '41'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '31'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '15'}]}
Status code: 200 32
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19550'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '17'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 33
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '19532'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '13', 'relevance': '93'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '79'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '57'}]}
Status code: 200 34
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '19511'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '18', 'relevance': '69'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '65'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '12', 'relevance': '46'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '38'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '27'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '23'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '23'}]}
Status code: 200 35
{'status': {'code': '0', 'msg': 'OK', 'credits': '23', 'remaining_credits': '19488'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '20', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '80'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '14', 'relevance': '70'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '70'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '65'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '30'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '25'}]}
Status code: 200 36
{'status': {'code': '0', 'msg': 'OK', 'credits': '5', 'remaining_credits': '19483'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 37
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '19479'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 38
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '19476'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '17'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 39
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '19463'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '83'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '33'}]}
Status code: 200 40
{'status': {'code': '0', 'msg': 'OK', 'credits': '31', 'remaining_credits': '19432'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '47', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '43', 'relevance': '91'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '35', 'relevance': '74'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '20', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '18', 'relevance': '38'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '34'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '32'}]}
Status code: 200 41
{'status': {'code': '0', 'msg': 'OK', 'credits': '30', 'remaining_credits': '19402'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '34', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '26', 'relevance': '76'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '22', 'relevance': '65'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '62'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '17', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '29'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '29'}]}
Status code: 200 42
{'status': {'code': '0', 'msg': 'OK', 'credits': '3', 'remaining_credits': '19399'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '100'}]}
Status code: 200 43
{'status': {'code': '0', 'msg': 'OK', 'credits': '17', 'remaining_credits': '19382'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '83'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '42'}]}
Status code: 200 44
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '19353'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '30', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '22', 'relevance': '73'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '19', 'relevance': '63'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '15', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '14', 'relevance': '47'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '33'}]}
Status code: 200 45
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19345'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '69'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '23'}]}
Status code: 200 46
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19337'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 47
{'status': {'code': '0', 'msg': 'OK', 'credits': '32', 'remaining_credits': '19305'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '26', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '21', 'relevance': '81'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '19', 'relevance': '73'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '18', 'relevance': '69'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '15', 'relevance': '58'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '54'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '54'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '15'}]}
Status code: 200 48
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '19298'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '20'}]}
Status code: 200 49
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '19289'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '88'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '38'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '12'}]}
Status code: 200 50
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '19276'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '42'}]}
Status code: 200 51
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '19270'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 52
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19256'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '90'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 53
{'status': {'code': '0', 'msg': 'OK', 'credits': '65', 'remaining_credits': '19191'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '81', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '57', 'relevance': '70'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '51', 'relevance': '63'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '45', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '42', 'relevance': '52'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '40', 'relevance': '49'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '32', 'relevance': '40'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '27', 'relevance': '33'}]}
Status code: 200 54
{'status': {'code': '0', 'msg': 'OK', 'credits': '16', 'remaining_credits': '19175'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '18', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '28'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '28'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '17'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '11'}]}
Status code: 200 55
{'status': {'code': '0', 'msg': 'OK', 'credits': '11', 'remaining_credits': '19164'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '12', 'relevance': '80'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '20'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '13'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '13'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '7'}]}
Status code: 200 56
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19156'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '17'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '17'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 57
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '19147'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '78'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '78'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 58
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19139'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '9'}]}
Status code: 200 59
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '19127'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 60
{'status': {'code': '0', 'msg': 'OK', 'credits': '16', 'remaining_credits': '19111'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '42'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 61
{'status': {'code': '0', 'msg': 'OK', 'credits': '5', 'remaining_credits': '19106'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 62
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '19102'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 63
{'status': {'code': '0', 'msg': 'OK', 'credits': '25', 'remaining_credits': '19077'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '18', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '16', 'relevance': '89'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '72'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '56'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '44'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '22'}]}
Status code: 200 64
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '19068'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 65
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '19062'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 66
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '19056'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '50'}]}
Status code: 200 67
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '19046'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '33'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '13'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '7'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '7'}]}
Status code: 200 68
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '19042'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '9'}]}
Status code: 200 69
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '19034'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 70
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '19015'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '20', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '20', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '14', 'relevance': '70'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '65'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '45'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '35'}]}
Status code: 200 71
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '19001'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '77'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '69'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '69'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '54'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '54'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '38'}]}
Status code: 200 72
{'status': {'code': '0', 'msg': 'OK', 'credits': '18', 'remaining_credits': '18983'}, 'category_list': [{'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '90'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '20'}]}
Status code: 200 73
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '18969'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '6', 'relevance': '60'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '60'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '10'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 74
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18959'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '78'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 75
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18951'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '33'}]}
Status code: 200 76
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '18945'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 77
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '18931'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '67'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '27'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '2', 'relevance': '13'}]}
Status code: 200 78
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18923'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 79
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18915'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '11'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '11'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 80
{'status': {'code': '0', 'msg': 'OK', 'credits': '36', 'remaining_credits': '18879'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '34', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '29', 'relevance': '85'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '25', 'relevance': '74'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '23', 'relevance': '68'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '20', 'relevance': '59'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '18', 'relevance': '53'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '16', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '29'}]}
Status code: 200 81
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18869'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '89'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 82
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '18862'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 83
{'status': {'code': '0', 'msg': 'OK', 'credits': '7', 'remaining_credits': '18855'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '86'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '71'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '57'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '29'}]}
Status code: 200 84
{'status': {'code': '0', 'msg': 'OK', 'credits': '17', 'remaining_credits': '18838'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '19', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '53'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '9', 'relevance': '47'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '21'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '21'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '16'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '5'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '5'}]}
Status code: 200 85
{'status': {'code': '0', 'msg': 'OK', 'credits': '15', 'remaining_credits': '18823'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '93'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '64'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 86
{'status': {'code': '0', 'msg': 'OK', 'credits': '39', 'remaining_credits': '18784'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '30', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '30', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '30', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '24', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '22', 'relevance': '73'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '21', 'relevance': '70'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '18', 'relevance': '60'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '30'}]}
Status code: 200 87
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18774'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '82'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '64'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '27'}]}
Status code: 200 88
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '18762'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '92'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '58'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 89
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '18753'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '9'}]}
Status code: 200 90
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '18732'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '15', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '14', 'relevance': '93'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '60'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '47'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '40'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '33'}]}
Status code: 200 91
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18724'}, 'category_list': [{'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '33'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 92
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '18710'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '22', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '64'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '12', 'relevance': '55'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '10', 'relevance': '45'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '41'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '18'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '4', 'relevance': '18'}]}
Status code: 200 93
{'status': {'code': '0', 'msg': 'OK', 'credits': '11', 'remaining_credits': '18699'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '15'}]}
Status code: 200 94
{'status': {'code': '0', 'msg': 'OK', 'credits': '5', 'remaining_credits': '18694'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 95
{'status': {'code': '0', 'msg': 'OK', 'credits': '15', 'remaining_credits': '18679'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '82'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '64'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '27'}]}
Status code: 200 96
{'status': {'code': '0', 'msg': 'OK', 'credits': '2', 'remaining_credits': '18677'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '50'}]}
Status code: 200 97
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '18668'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '60'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 98
{'status': {'code': '0', 'msg': 'OK', 'credits': '20', 'remaining_credits': '18648'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '20', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '70'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '40'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '30'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '5'}]}
Status code: 200 99
{'status': {'code': '0', 'msg': 'OK', 'credits': '22', 'remaining_credits': '18626'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '82'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '73'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '64'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '55'}]}
Status code: 200 100
{'status': {'code': '0', 'msg': 'OK', 'credits': '15', 'remaining_credits': '18611'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '54'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '15'}]}
Status code: 200 101
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '18598'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '7', 'relevance': '50'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '36'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '7'}]}
Status code: 200 102
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18590'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '7', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '43'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '14'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '14'}]}
Status code: 200 103
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '18578'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '38'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 104
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '18565'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '83'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '4', 'relevance': '67'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '17'}]}
Status code: 200 105
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18557'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '13', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '6', 'relevance': '46'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '31'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '23'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '15'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '1', 'relevance': '8'}]}
Status code: 200 106
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '18548'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '10'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 107
{'status': {'code': '0', 'msg': 'OK', 'credits': '13', 'remaining_credits': '18535'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '43'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '14'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 108
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18527'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '60'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '40'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 109
{'status': {'code': '0', 'msg': 'OK', 'credits': '19', 'remaining_credits': '18508'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '18', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '17', 'relevance': '94'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '15', 'relevance': '83'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '15', 'relevance': '83'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '15', 'relevance': '83'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '13', 'relevance': '72'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '67'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '50'}]}
Status code: 200 110
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '18504'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '25'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 111
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18496'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '9', 'relevance': '82'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '18'}]}
Status code: 200 112
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18486'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '7', 'relevance': '88'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '88'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '5', 'relevance': '62'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '62'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '12'}]}
Status code: 200 113
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '18480'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '8', 'relevance': '89'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 114
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18472'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '55'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '18'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '9'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '9'}]}
Status code: 200 115
{'status': {'code': '0', 'msg': 'OK', 'credits': '5', 'remaining_credits': '18467'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 116
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '18463'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '1', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '100'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '1', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '100'}]}
Status code: 200 117
{'status': {'code': '0', 'msg': 'OK', 'credits': '8', 'remaining_credits': '18455'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '60'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 118
{'status': {'code': '0', 'msg': 'OK', 'credits': '21', 'remaining_credits': '18434'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '22', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '17', 'relevance': '77'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '15', 'relevance': '68'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '14', 'relevance': '64'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '12', 'relevance': '55'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '9', 'relevance': '41'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '5', 'relevance': '23'}]}
Status code: 200 119
{'status': {'code': '0', 'msg': 'OK', 'credits': '2', 'remaining_credits': '18432'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '33'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '1', 'relevance': '33'}]}
Status code: 200 120
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '18426'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '100'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '80'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '40'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '20'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '1', 'relevance': '20'}]}
Status code: 200 121
{'status': {'code': '0', 'msg': 'OK', 'credits': '1', 'remaining_credits': '18425'}, 'category_list': []}
Status code: 200 122
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18415'}, 'category_list': [{'code': 'Trust', 'label': 'Trust', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '90'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '90'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '8', 'relevance': '80'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '7', 'relevance': '70'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '7', 'relevance': '70'}]}
Status code: 200 123
{'status': {'code': '0', 'msg': 'OK', 'credits': '10', 'remaining_credits': '18405'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '11', 'relevance': '92'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '83'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '33'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '25'}]}
Status code: 200 124
{'status': {'code': '0', 'msg': 'OK', 'credits': '9', 'remaining_credits': '18396'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '8', 'relevance': '100'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '88'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '62'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '25'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '2', 'relevance': '25'}]}
Status code: 200 125
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '18384'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '11', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '10', 'relevance': '91'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '8', 'relevance': '73'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '5', 'relevance': '45'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '4', 'relevance': '36'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '27'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '27'}]}
Status code: 200 126
{'status': {'code': '0', 'msg': 'OK', 'credits': '6', 'remaining_credits': '18378'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '100'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '67'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '5', 'relevance': '56'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '4', 'relevance': '44'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '22'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '1', 'relevance': '11'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '11'}]}
Status code: 200 127
{'status': {'code': '0', 'msg': 'OK', 'credits': '12', 'remaining_credits': '18366'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '12', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '9', 'relevance': '75'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '6', 'relevance': '50'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '2', 'relevance': '17'}]}
Status code: 200 128
{'status': {'code': '0', 'msg': 'OK', 'credits': '5', 'remaining_credits': '18361'}, 'category_list': [{'code': 'Fear', 'label': 'Fear', 'abs_relevance': '4', 'relevance': '100'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '3', 'relevance': '75'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '2', 'relevance': '50'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '25'}]}
Status code: 200 129
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '18347'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '86'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '10', 'relevance': '71'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '8', 'relevance': '57'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '4', 'relevance': '29'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '3', 'relevance': '21'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '2', 'relevance': '14'}]}
Status code: 200 130
{'status': {'code': '0', 'msg': 'OK', 'credits': '4', 'remaining_credits': '18343'}, 'category_list': [{'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '10', 'relevance': '100'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '30'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '2', 'relevance': '20'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '1', 'relevance': '10'}]}
Status code: 200 131
{'status': {'code': '0', 'msg': 'OK', 'credits': '14', 'remaining_credits': '18329'}, 'category_list': [{'code': 'Joy', 'label': 'Joy', 'abs_relevance': '21', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '11', 'relevance': '52'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '8', 'relevance': '38'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '8', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '7', 'relevance': '33'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '6', 'relevance': '29'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '4', 'relevance': '19'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '3', 'relevance': '14'}]}
Status code: 200 132
{'status': {'code': '0', 'msg': 'OK', 'credits': '29', 'remaining_credits': '18300'}, 'category_list': [{'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '31', 'relevance': '100'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '25', 'relevance': '81'}, {'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '68'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '20', 'relevance': '65'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '17', 'relevance': '55'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '12', 'relevance': '39'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '8', 'relevance': '26'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '5', 'relevance': '16'}]}
Status code: 200 133
{'status': {'code': '0', 'msg': 'OK', 'credits': '27', 'remaining_credits': '18273'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '21', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '18', 'relevance': '86'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '18', 'relevance': '86'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '17', 'relevance': '81'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '14', 'relevance': '67'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '11', 'relevance': '52'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '10', 'relevance': '48'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '9', 'relevance': '43'}]}
Status code: 200 134
{'status': {'code': '0', 'msg': 'OK', 'credits': '39', 'remaining_credits': '18234'}, 'category_list': [{'code': 'Anger', 'label': 'Anger', 'abs_relevance': '34', 'relevance': '100'}, {'code': 'Fear', 'label': 'Fear', 'abs_relevance': '25', 'relevance': '74'}, {'code': 'Sadness', 'label': 'Sadness', 'abs_relevance': '21', 'relevance': '62'}, {'code': 'Anticipation', 'label': 'Anticipation', 'abs_relevance': '16', 'relevance': '47'}, {'code': 'Joy', 'label': 'Joy', 'abs_relevance': '16', 'relevance': '47'}, {'code': 'Trust', 'label': 'Trust', 'abs_relevance': '14', 'relevance': '41'}, {'code': 'Surprise', 'label': 'Surprise', 'abs_relevance': '13', 'relevance': '38'}, {'code': 'Disgust', 'label': 'Disgust', 'abs_relevance': '9', 'relevance': '26'}]}
]